language: elixir
elixir:
  - 1.2.0
env: MIX_ENV=test
sudo: false # faster builds
notifications:
  email: false
script:
  - mix compile --warnings-as-errors
  - mix test
  - mix credo
  - mix dogma
services:
  - postgresql
before_script:
  - psql -c 'create database identificator_test;' -U postgres
