language: elixir
elixir:
  - 1.2.4
env: MIX_ENV=test
sudo: false
notifications:
  email: false
script:
  - mix compile
  - mix test
  - mix credo --strict
  - mix dogma
services:
  - postgresql
before_script:
  - psql -c 'create database identificator_test;' -U postgres
addons:
  postgresql: "9.4"
